import img1 from "../assets/img/сard1.jpeg";
import img2 from "../assets/img/сard2.jpeg";
export const mockData = [
  {
    id: "663c7...a2d1",
    title: "Пролет №1",
    image: img1,
    fileType: "Фото",
    fileCount: 12,
    addedDate: "23.01.2023",
    tags: [
      { text: "#Лес", color: "var(--green)" },
      { text: "#Кадры", color: "var(--orange)" },
    ],
    properties: { нейросети: true },
    quantity: 12,
  },
  {
    id: "91f2b...d8e3",
    title: "Пролет №2",
    image: img2,
    fileType: "Видео",
    fileCount: 8,
    addedDate: "10.02.2023",
    tags: [
      { text: "#Горы", color: "var(--green)" },
      { text: "#Съемка", color: "var(--red)" },
    ],
    properties: { нейросети: false },
    quantity: 8,
  },
  {
    id: "6b4e1...f5c9",
    title: "Пролет №3",
    image: img2,
    fileType: "Фото",
    fileCount: 15,
    addedDate: "05.03.2023",
    tags: [
      { text: "#Лес", color: "var(--green)" },
      { text: "#Кадры", color: "var(--orange)" },
    ],
    properties: { нейросети: true },
    quantity: 15,
  },
  {
    id: "c3d7f...a982",
    title: "Пролет №4",
    image: img1,
    fileType: "Видео",
    fileCount: 10,
    addedDate: "19.04.2023",
    tags: [
      { text: "#Горы", color: "var(--green)" },
      { text: "#Съемка", color: "var(--red)" },
    ],
    properties: { нейросети: false },
    quantity: 10,
  },
  {
    id: "e52b9...d3f4",
    title: "Пролет №5",
    image: img1,
    fileType: "Фото",
    fileCount: 20,
    addedDate: "12.05.2023",
    tags: [
      { text: "#Лес", color: "var(--green)" },
      { text: "#Кадры", color: "var(--orange)" },
    ],
    properties: { нейросети: true },
    quantity: 20,
  },
  {
    id: "fa8c3...b7e1",
    title: "Пролет №6",
    image: img2,
    fileType: "Фото",
    fileCount: 7,
    addedDate: "25.06.2023",
    tags: [
      { text: "#Горы", color: "var(--green)" },
      { text: "#Съемка", color: "var(--red)" },
    ],
    properties: { нейросети: false },
    quantity: 7,
  },
  {
    id: "2b9d4...f8a5",
    title: "Пролет №7",
    image: img1,
    fileType: "Видео",
    fileCount: 14,
    addedDate: "03.07.2023",
    tags: [
      { text: "#Лес", color: "var(--green)" },
      { text: "#Кадры", color: "var(--orange)" },
    ],
    properties: { нейросети: true },
    quantity: 14,
  },
  {
    id: "5c2e8...d6b9",
    title: "Пролет №8",
    image: img1,
    fileType: "Фото",
    fileCount: 11,
    addedDate: "17.08.2023",
    tags: [
      { text: "#Горы", color: "var(--green)" },
      { text: "#Съемка", color: "var(--red)" },
    ],
    properties: { нейросети: false },
    quantity: 11,
  },
  {
    id: "d7f1c...e9a4",
    title: "Пролет №9",
    image: img2,
    fileType: "Видео",
    fileCount: 9,
    addedDate: "22.09.2023",
    tags: [
      { text: "#Лес", color: "var(--green)" },
      { text: "#Кадры", color: "var(--orange)" },
    ],
    properties: { нейросети: true },
    quantity: 9,
  },
  {
    id: "a9b3e...c5d2",
    title: "Пролет №10",
    image: img1,
    fileType: "Фото",
    fileCount: 13,
    addedDate: "10.10.2023",
    tags: [
      { text: "#Горы", color: "var(--green)" },
      { text: "#Съемка", color: "var(--red)" },
    ],
    properties: { нейросети: false },
    quantity: 13,
  },
];
